### ISSUE TITLE
hard coded lmax settings

### ISSUE THREAD

**Issue by DanNBullock** [brain-life/app-ensembletracking#1]
L max settings should not be hard coded to progress all the way up to lmax 12.  You should detect the maximum lmax setting from the number of angles in your data.

**Comment by kitchell** [comment]
@DanNBullock can you give me code to do this? what number of angles = what lmaz setting?

**Comment by soichih** [comment]
Here is semi-working python code that uses .bvals to compute optimal LMAX

```
#get non0 bvals
f = open('test.bvals', 'r')
line = f.readline().strip().replace(",", " ")
bvals = line.split(" ")
bvals_non0 = filter(lambda v: v != "0", bvals)
count=len(bvals_non0);

#calculate max lmax (6->2, 15->4, 28->6, etc..)
lmax=0
while (lmax+3)*(lmax+4)/2 <= count:
       lmax+=2

print "lmax should be ", lmax, "for bvals:", count
```

**Comment by kitchell** [comment]
Ok I have added these changes and it should now calculate the max lmax value
