### ISSUE TITLE
Show final track.tck fiber count

### ISSUE THREAD

**Issue by soichih** [brain-life/app-ensembletracking#13]
It would be nice if this app showed the final fiber count for track.tck somewhere (maybe in product.json?) It can also show counts from various algorithm before aggregated into track.tck.

**Comment by bcmcpher** [comment]
I have it checking the final count now and failing if it does not match the
expected output number. Grabbing into products.json would be easy.

The counts of the individual parameters would be nice, but it'd be more
work and with the global count check in place I'm not sure how necessary it
is.

How would I add count to products.json?

**Comment by soichih** [comment]
You can just dump any data to product.json (used to be products.json), and it will be picked up by Amaretti and displayed in UI - as raw JSON (maybe we can come up with some standard so that we can display them in nice charts / graphs, etc.. eventually)

**Comment by bcmcpher** [comment]
Alright. The app succeeded finally, so it's ready to merge. If you're
around tomorrow I can check with you and add the count output when it
merges.
