### ISSUE TITLE
Large amount of stderr log

### ISSUE THREAD

**Issue by soichih** [brain-life/app-ensembletracking#2]
This app currently generates large amount of verbose output which is making it difficult to troubleshoot.

My log is about 297MB and it largely contains output that looks like 

```
...
  374298 generated,   326429 selected    [ 65%]
  374299 generated,   326430 selected    [ 65%]
  374300 generated,   326431 selected    [ 65%]
  374301 generated,   326432 selected    [ 65%]
  374302 generated,   326433 selected    [ 65%]
  374303 generated,   326434 selected    [ 65%]
  374304 generated,   326435 selected    [ 65%]
  374305 generated,   326436 selected    [ 65%]
  374306 generated,   326437 selected    [ 65%]
  374307 generated,   326438 selected    [ 65%]
  374308 generated,   326439 selected    [ 65%]
  374309 generated,   326440 selected    [ 65%]
  374310 generated,   326441 selected    [ 65%]
  374311 generated,   326442 selected    [ 65%]
  374312 generated,   326443 selected    [ 65%]
  374313 generated,   326444 selected    [ 65%]
  374315 generated,   326445 selected    [ 65%]
...
```

Can you silence this output - or make it much less verbose?

**Comment by francopestilli** [comment]
pip[e this to devnull?

**Comment by soichih** [comment]
The log is much smaller now (33MB) but still seeing a tons of following output.

```
csdeconv: failed to converge
csdeconv: failed to converge
csdeconv: failed to converge
csdeconv: failed to converge
csdeconv: failed to converge
csdeconv: not enough negative directions! failed to converge.
csdeconv: failed to converge
csdeconv: failed to converge
csdeconv: failed to converge
csdeconv: failed to converge
...
```

**Comment by kitchell** [comment]
This output is ok, but im not sure how to have it not show.  

http://jdtournier.github.io/mrtrix-0.2/faq.html#converge

http://www.nitrc.org/pipermail/mrtrix-discussion/2011-December/000338.html

**Comment by soichih** [comment]
Thanks for the links.

They say..
> if you are getting a lot of these messages, you may need to check that the CSD images are suitable.
> You'll get bigger problems if you get "not enough negative directions" messages. In these cases, the affected voxels are assigned a NaN value, and so can't be tracked through. Note this only happens when using super-resolution (i.e. lmax is greater than the data can natively support).

@DanNBullock was saying that lmax needs to be adjusted for each data.. 
> https://github.com/brain-life/app-ensembletracking/issues/1

You don't think this is related to that?

**Comment by kitchell** [comment]
I think it is. because we always go to lmax 12 when the data may not support that high of an lmax. but since it is ensemble, it is not a huge deal. We should make the change Dan suggested, but I am not sure how yet.

**Comment by kitchell** [comment]
should we quiet the csdeconv output? (the one printing csdeconv: failed to converge
csdeconv: failed to converge ...)

**Comment by soichih** [comment]
Various patches we made to silence verbose logs and updates to use proper max-lmax seem to have cured this problem. 

If we want to, we could update status.sh to detect large number of "not enough negative directions" (grep | wc -l) and stop the process.

**Comment by soichih** [comment]
@kitchell Yes, we should add -quiet to csdeconv. I think I forgot to add it.

**Comment by kitchell** [comment]
it is added
