### ISSUE TITLE
The output track.tck is 22.3GB

### ISSUE THREAD

**Issue by soichih** [brain-life/app-ensembletracking#4]
I've switched the tracking app for old Brain-Life workflow for LiFE from app-tracking to app-ensembletracking, and ran it with the first sample data (STN.sub-FP.run01_fliprot_aligned_trilin http://purl.stanford.edu/cs392kv3054).

The output from the app was 22.3GB behemoth and when I ran LiFE on it, it timed out after 3 hours (it looks like it would have taken more than 15 hours?)

![fireshot capture 5 - white matter tracts_ - https___brain-life org_majortracts_](https://user-images.githubusercontent.com/923896/28650382-9dc0a53e-7249-11e7-9049-910bc5fe25e8.png)

The 22.3GB output is probably unsustainable for a large number of subjects. Is there something wrong with the app, or input data?

**Comment by francopestilli** [comment]
This must be an error. If you are using the older life code from
GitHub/Franco Pestilli/life it is possible that .tck us the .mat fe
structure that can be very large.

The code we should use us GitHub/brain-life/encode

@ccaiafa

Franco

sent via phone, pardon brevity and mistakes.

**Comment by soichih** [comment]
@francopestilli I should be using the latest version of LiFE from brain-life/encode repo. I did pull recently.

Are you saying that it's an error with LiFE and 22G track.tck output from ensemble is normal?

**Comment by soichih** [comment]
Sorry, I just realized that app-ensembletracking uses much less fiber/fiber_max count than app-tracking. I think this explains why it was generating such a large output. I've reconfigured the defaults, and resubmitted some tests.

**Comment by francopestilli** [comment]
Good!

Franco

sent via phone, pardon brevity and mistakes.
