### ISSUE TITLE
Timeout on Karst

### ISSUE THREAD

**Issue by soichih** [brain-life/app-ensembletracking#5]
I just ran this app and got executed on Karst. The app failed with following error message.

```
csdeconv: failed to converge
csdeconv: failed to converge
csdeconv: failed to converge
csdeconv: failed to converge
=>> PBS: job killed: walltime 23444 exceeded limit 23400
```

Maybe the timeout should be increased? Or is this just a symptom of something not working right?

**Comment by kitchell** [comment]
I have never run out of time when submitting through brain life, but I think it always goes to carbonate. I was going to say we should increase the time, but Im not sure that something is not going wrong. I just checked my old scripts and I used to only ask for 3 hours on karst (https://github.com/kitchell/HCP_Diffusion_Scripts/blob/master/HCP_run_ensemble.pbs#L3).

What data are you using?
