### ISSUE TITLE
fibers / fibers_max should be divided?

### ISSUE THREAD

**Issue by soichih** [brain-life/app-ensembletracking#7]
A user has submitted app-ensembletracking with fibers set to 500000 - because he thought that this parameters sets the number of output fibers. In reality, it created 500000 x 13 fibers and output track.tck was 24G in size. This led to timeout on subsequent app (app-life).

I believe the input fibers should be divided by the total number of tracking to be executed so that the final track.tck will contain the number of fibers specified by the user - as expected.

**Comment by francopestilli** [comment]
I agree with your suggestion. nOutputFibers = round(nRequestedFibers / 13 )

**Comment by kitchell** [comment]
ok I can make this change, but it is via a shell script not matlab so I may need help writing it out.

**Comment by kitchell** [comment]
actually, no this doesn't work because there may not always be 13 tcks generated. depending on the max lmax the number will change

**Comment by soichih** [comment]
We could do something like following

[calculatetracks.py]
```
#!/usr/bin/env python

#this script calcualtes number of expected output tracks based on config.json and lmax as input (from calculatelmax.py)
# ./calculatetracks.py $MAXLMAX

import json
import sys

maxlmax = int(sys.argv[1])
tracks_per_algorithm=len(range(2, maxlmax+2, 2))

with open('config.json') as config_json:
    config = json.load(config_json)
    tracks = 0
    if config['do_tensor']: tracks+=1 
    if config['do_probabilistic']: tracks+=tracks_per_algorithm 
    if config['do_deterministic']: tracks+=tracks_per_algorithm 

    print tracks
```

Sample output with all 3 do_xxx set to true

```
$ ./calculatetracks.py 12
13
```

**Comment by kitchell** [comment]
ok I am making this change, but then the fibers max variable doesn't make sense. Should I just set it to double the number?

**Comment by soichih** [comment]
I don't quite understand how -maxnum is used - from the streamtrack -h 

```
  -number tracks  set the desired number of tracks. The program will continue
                to generate tracks until this number of tracks have been
                selected and written to the output file (default is 100 for
                *_STREAM methods, 1000 for *_PROB methods).

                tracks: the number of tracks.

  -maxnum tracks  set the maximum number of tracks to generate. The program
                will not generate more tracks than this number, even if the
                desired number of tracks hasn't yet been reached (default is
                100 x number). Specifying zero for this option removes any
                limit - the algorithm will keep generating tracks until the
                number required has been reached.

                tracks: the maximum number of tracks.

```

But.. can't we just divide user specified fiber_max with the same numerator given by calculatetracks?

**Comment by kitchell** [comment]
so my understanding is this: say number tracks is set to 60,000. mrtrix will first try to make 60,000 streamlines, but a streamline can fail, so after trying 60,000 times if some have failed it will continue to try to reach that number up to the maxnum of tracks. if maxnum is set to 100,000 then it will try up to 100,000 times to make 60,000 streamlines. even if it doesnt reach 60,000 streamlines, it will stop after trying 100,000 times. So a total max number for all tracking doesnt really make sense. we could just use the mrtrix default and set max number = 100 X numfibers. before I had it set to 100,000 for a numfiber of 60,000

**Comment by soichih** [comment]
Ah, thanks for the explanation; it makes sense now. 

I would remove fiber_max option and just let streamtrack to use the default value - to make things easier for the user. Or setting it to double the -number like you suggested.

**Comment by kitchell** [comment]
ok ive removed it and set it to double the number for now, the default (100x) seems like too much.

**Comment by soichih** [comment]
Thanks for the update. I've made a few more minor updates to submit.pbs.

I just submitted a test task with following parameter

>    "fibers": 660000,
>    "do_deterministic": true,
>    "do_probabilistic": true,
>    "do_tensor": true,

The stdout says

> Using MAXLMAX: 12
> Using NUMFIBERS per each track: 50769
> Using MAXNUMBERFIBERSATTEMPTED 101538

And it produces track.tck with 

> count: 659997

I think its pretty close the the fiber count I've requested. I think it's all good. Closing this ticket.
