### ISSUE TITLE
We shouldn't set ppn=16 for carbonate

### ISSUE THREAD

**Issue by soichih** [brain-life/app-ensembletracking#9]
ppn=16 works fine on karst  (since there are only 16 cores), but for carbonate, it could end up wasting cores since it has 24 cores available (unless someone runs ppn=8 jobs).

We might need to increase the walltime, but I think setting ppn=8 will allow it to run on 3 ways parallel on carbonate (and 2 way on karst). We should experiment.

**Comment by kitchell** [comment]
it is set to 8 now, but we need to test the time
